### ISSUE TITLE
FileNotFoundError:  No such file or directory: '/selenium_testing_library/main.js'

### ISSUE THREAD

**Issue by danhayden** [anze3db/selenium-testing-library#147]
**Describe the bug**
Importing Screen results in a FileNotFoundError when it gets to  `testing_library = (Path(__file__).parent / Path("main.js")).read_text()`

**To Reproduce**
1. Create new file with `from selenium_testing_library import Screen`
2. Run file

**Comment by anze3db** [comment]
@danhayden thank you for the bug report. I have fixed the issue in the latest release https://github.com/anze3db/selenium-testing-library/releases/tag/2024.2
